TEXTS = {
    "ar": {
        # Welcome
        "welcome_new": "🤍 أهلاً بك في Always Close\n\nاختر نوعك:",
        "welcome_back": "🤍 مرحباً بعودتك!",
        # Profile setup
        "choose_gender": "👤 اختر نوعك:",
        "btn_male": "👨 ذكر",
        "btn_female": "👩 أنثى",
        "enter_birthdate": "🎂 اكتب تاريخ ميلادك بالشكل:\n1998-05-10",
        "enter_bio": "📝 اكتب نبذة عن نفسك:",
        "invalid_date": "❌ التاريخ غير صحيح. اكتبه:\n1998-05-10",
        "profile_saved": "✅ تم حفظ بياناتك 🎉",
        "updated": "✅ تم التحديث",
        # Contact / Location
        "phone_saved": "📱 تم حفظ رقم الهاتف ✅",
        "location_updated": "🚀 تم تحديث موقعك بنجاح!",
        "registration_error": "❌ خطأ في التسجيل.",
        # Errors
        "register_first": "❌ يجب التسجيل أولاً.",
        "share_location_first": "❌ شارك موقعك أولاً.",
        "no_nearby": "❌ لا يوجد أشخاص قريبين حالياً.",
        "error": "❌ حدث خطأ.",
        "register_first_answer": "❌ سجّل أولاً",
        "error_answer": "❌ خطأ",
        # Matches / Requests
        "no_matches": "لا يوجد تطابقات بعد 🔥",
        "matches_title": "🔥 تطابقاتك:\n\n",
        "no_requests": "لا يوجد طلبات إعجاب بعد 📥",
        "requests_title": "📥 الأشخاص الذين أعجبوا بك:\n\n",
        # Visibility
        "account_visible": "✅ حسابك مرئي الآن.",
        "account_hidden": "👻 تم إخفاء حسابك.",
        "phone_visible": "📞 رقمك مرئي الآن.",
        "phone_hidden": "🔒 تم إخفاء رقمك.",
        # Edit profile
        "what_to_edit": "✏️ ماذا تريد تعديله؟",
        "enter_birthdate_edit": "🎂 اكتب التاريخ:\n1998-05-10",
        "enter_bio_edit": "📝 اكتب النبذة الجديدة:",
        # Card
        "user_label": "مستخدم",
        "unknown_gender": "غير محدد",
        "gender_male": "ذكر",
        "gender_female": "أنثى",
        "unknown_distance": "غير معروف",
        "active_now": "🟢 نشط الآن",
        "last_seen": "🕒 منذ {} {}",
        "unknown_label": "مجهول",
        # Card units
        "years_unit": "سنة",
        "km_unit": "كم",
        "min_unit": "دقيقة",
        "hour_unit": "ساعة",
        "day_unit": "يوم",
        "now_unit": "الآن",
        # Mutual match
        "mutual_match": "🎉 تم التطابق! يمكنكما التواصل الآن.",
        # Answers
        "answer_liked": "تم الإعجاب ❤️",
        "answer_match": "🎉 تطابق!",
        "answer_superlike": "⭐ سوبر لايك!",
        # Main keyboard buttons
        "btn_share_phone": "📱 تسجيل الهاتف",
        "btn_share_location": "📍 مشاركة الموقع",
        "btn_view_nearby": "👥 عرض الأقرب",
        "btn_matches": "🔥 التطابقات",
        "btn_requests": "📥 طلباتي",
        "btn_hide": "👻 إخفاء حسابي",
        "btn_phone_toggle": "📞 إظهار/إخفاء رقمي",
        "btn_edit": "✏️ تعديل بياناتي",
        # Card buttons
        "btn_prev": "⬅️ السابق",
        "btn_next": "التالي ➡️",
        "btn_like": "❤️ إعجاب",
        "btn_superlike": "⭐ سوبر",
        "btn_skip": "❌ تخطي",
        "btn_message": "💬 مراسلة",
        # Edit keyboard buttons
        "btn_edit_gender": "👤 تعديل النوع",
        "btn_edit_birthdate": "🎂 تعديل تاريخ الميلاد",
        "btn_edit_bio": "📝 تعديل النبذة",
        # Last seen label
        "last_seen_label": "آخر ظهور:",
        # Map
        "btn_map": "🗺️ الخريطة",
        "map_tap": "🗺️ اضغط لفتح الخريطة التفاعلية\n\n📍 موقعك بدبوس أحمر\n🔵 المستخدمون القريبون بدبابيس زرقاء\nاضغط على أي دبوس لعرض الملف الشخصي",
        "map_btn_open": "🗺️ فتح الخريطة",
        "map_no_location": "❌ شارك موقعك أولاً ثم افتح الخريطة.",
        "map_not_registered": "❌ يجب التسجيل أولاً.",
        # Profile
        "btn_profile": "👤 ملفي الشخصي",
        "profile_tap": "👤 اضغط لفتح ملفك الشخصي",
        "profile_btn_open": "👤 فتح الملف الشخصي",
        # Settings
        "btn_settings": "⚙️ الإعدادات",
        "settings_tap": "⚙️ اضغط لفتح صفحة الإعدادات",
        "settings_btn_open": "⚙️ فتح الإعدادات",
        # Rooms nearby & create
        "btn_rooms_nearby": "📍 الغرف القريبة",
        "btn_create_room": "🏠 إنشاء غرفة",
        "room_loc_snapshot":  "📍 موقعك الحالي سيُسجَّل كموقع ثابت للغرفة.\n\n",
        "room_no_location":   "⚠️ لم يُعثر على موقعك. افتح الخريطة أولاً لتفعيل الموقع — ستُنشأ الغرفة بدون إحداثيات وقد لا تظهر على الخريطة.\n\n",
        "create_room_ask_name": "🏠 اكتب اسم الغرفة:",
        "create_room_ask_purpose": "📝 اكتب هدف أو وصف الغرفة:",
        "room_created": "✅ تم إنشاء الغرفة بنجاح!\n🏠 الاسم: {}\n📝 الهدف: {}",
        "room_create_error": "❌ خطأ في إنشاء الغرفة. تأكد أن قاعدة البيانات جاهزة.",
        "room_join_request": "📩 طلب انضمام جديد لغرفتك «{}» من @{}",
        "btn_accept": "✅ قبول",
        "btn_reject": "❌ رفض",
        "room_accepted": "✅ تم قبول طلب الانضمام.",
        "room_rejected": "❌ تم رفض طلب الانضمام.",
        "room_you_accepted": "✅ تم قبولك في غرفة «{}»!",
        "room_you_rejected": "❌ تم رفض طلب انضمامك لغرفة «{}».",
        "room_cancel": "❌ تم إلغاء إنشاء الغرفة.",
        "btn_cancel_action": "❌ إلغاء",
        "create_room_ask_nature": "🏷️ اختر طبيعة الغرفة:",
        "nature_social": "🤝 اجتماعية",
        "nature_edu": "📚 تعليمية",
        "nature_fun": "🎭 ترفيهية",
        "nature_work": "💼 عمل",
        "nature_sport": "⚽ رياضية",
        "nature_other": "📌 أخرى",
        "create_room_ask_expires": "⏳ كم مدة الغرفة؟",
        "expires_1d": "⏰ يوم واحد",
        "expires_3d": "📅 3 أيام",
        "expires_1w": "🗓️ أسبوع",
        "expires_1m": "📆 شهر",
        "expires_forever": "♾️ دائمة",
        "room_join_ok": "✅ تم الانضمام لغرفة «{}» بنجاح!",
        "room_join_already": "ℹ️ أنت بالفعل عضو في هذه الغرفة.",
        "room_join_error": "❌ خطأ في الانضمام للغرفة.",
        "room_delete_ok": "🗑️ تم حذف الغرفة بنجاح.",
        "room_delete_no_perm": "❌ لا يمكن الحذف: أنت لست المنشئ أو هناك أعضاء آخرون.",
        "room_delete_error": "❌ خطأ في حذف الغرفة.",
        "room_image_ok": "✅ تم حفظ صورة الغرفة.",
        "room_image_del_ok": "✅ تم حذف صورة الغرفة.",
        # Users list
        "btn_users_list": "👥 قائمة المستخدمين",
        "users_tap": "👥 اضغط لعرض المستخدمين القريبين",
        "users_btn_open": "👥 فتح القائمة",
        "users_no_location": "❌ شارك موقعك أولاً ثم افتح القائمة.",
        "users_not_registered": "❌ يجب التسجيل أولاً.",
        # Rooms list
        "btn_rooms_list": "🏠 قائمة الغرف",
        "rooms_list_tap": "🏠 اضغط لعرض الغرف القريبة",
        "rooms_list_btn_open": "🏠 فتح قائمة الغرف",
        "rooms_list_no_location": "❌ شارك موقعك أولاً ثم افتح قائمة الغرف.",
        "rooms_list_not_registered": "❌ يجب التسجيل أولاً.",
        "room_limit_reached": "❌ وصلت للحد الأقصى (3 غرف). احذف غرفة أولاً.",
        # Stores
        "btn_stores_list": "🏪 قائمة المتاجر",
        "btn_create_store": "🛍️ إنشاء متجر",
        "btn_stores_nearby": "📍 المتاجر القريبة",
        "stores_list_tap": "🏪 اضغط لعرض المتاجر القريبة",
        "stores_list_btn_open": "🏪 فتح قائمة المتاجر",
        "stores_list_no_location": "❌ شارك موقعك أولاً ثم افتح قائمة المتاجر.",
        "stores_list_not_registered": "❌ يجب التسجيل أولاً.",
        "store_limit_reached": "❌ وصلت للحد الأقصى (3 متاجر). احذف متجراً أولاً.",
        "store_loc_snapshot":  "📍 موقعك الحالي سيُسجَّل كموقع ثابت للمتجر.\n\n",
        "store_no_location":   "⚠️ لم يُعثر على موقعك. افتح الخريطة أولاً لتفعيل الموقع — سيُنشأ المتجر بدون إحداثيات وقد لا يظهر على الخريطة.\n\n",
        "create_store_ask_name": "🏪 اكتب اسم المتجر:",
        "create_store_ask_purpose": "📝 اكتب وصف أو هدف المتجر:",
        "create_store_ask_nature": "🏷️ اختر نوع المتجر:",
        "store_nature_grocery": "🛒 بقالة",
        "store_nature_food": "🍔 مطعم / طعام",
        "store_nature_clothing": "👕 ملابس",
        "store_nature_electronics": "📱 إلكترونيات",
        "store_nature_beauty": "💄 جمال وعناية",
        "store_nature_services": "🔧 خدمات",
        "store_nature_other": "📦 أخرى",
        "create_store_ask_expires": "⏳ كم مدة المتجر؟",
        "store_created": "✅ تم إنشاء المتجر بنجاح!\n🏪 الاسم: {}\n📝 الوصف: {}",
        "store_create_error": "❌ خطأ في إنشاء المتجر. تأكد أن قاعدة البيانات جاهزة.",
        "store_cancel": "❌ تم إلغاء إنشاء المتجر.",
        "nearby_stores": "📍 المتاجر القريبة:",
        # Chat system
        "btn_public_chat":     "💬 الدردشة العامة",
        "btn_room_chats":      "🏠 دردشة الغرف",
        "btn_store_chats":     "🏪 دردشة المتاجر",
        "btn_exit_chat":       "❌ خروج من الدردشة",
        "chat_select_room":    "🏠 اختر الغرفة للدردشة:",
        "chat_select_store":   "🏪 اختر المتجر للدردشة:",
        "chat_no_rooms":       "❌ أنت لست عضواً في أي غرفة. انضم لغرفة أولاً.",
        "chat_no_stores":      "❌ أنت لا تتابع أي متجر. تابع متجراً أولاً.",
        "chat_room_joined":    "✅ دخلت دردشة غرفة «{}»\n\nأرسل أي رسالة أو صورة أو ملف أو ستيكر وستصل لجميع الأعضاء.\n\nاضغط الزر بالأسفل للخروج.",
        "chat_store_joined":   "✅ دخلت دردشة متجر «{}»\n\nأرسل أي رسالة أو صورة أو ملف أو ستيكر وستصل لجميع المتابعين.\n\nاضغط الزر بالأسفل للخروج.",
        "chat_exited":         "✅ خرجت من الدردشة.",
        "chat_from":           "💬 {} — غرفة «{}»",
        "chat_from_store":     "🏪 {} — متجر «{}»",
        "chat_private_from":   "🔒 رسالة خاصة من {}",
        "chat_btn_private":    "💬 مراسلة خاصة",
        "chat_btn_reply":      "↩️ رد خاص",
        "chat_btn_exit":       "❌ خروج من الدردشة",
        "chat_private_started":"🔒 بدأت محادثة خاصة مع {}\nأرسل أي رسالة وستصله مباشرة.\nاضغط الزر بالأسفل للخروج.",
        "chat_private_notify": "🔒 {} بدأ محادثة خاصة معك.",
        "chat_no_members":     "ℹ️ لا يوجد أعضاء آخرون في الغرفة/المتجر الآن.",
    },
    "en": {
        # Welcome
        "welcome_new": "🤍 Welcome to Always Close\n\nChoose your gender:",
        "welcome_back": "🤍 Welcome Back!",
        # Profile setup
        "choose_gender": "👤 Choose your gender:",
        "btn_male": "👨 Male",
        "btn_female": "👩 Female",
        "enter_birthdate": "🎂 Enter your birthdate:\n1998-05-10",
        "enter_bio": "📝 Write a short bio about yourself:",
        "invalid_date": "❌ Invalid date. Use format:\n1998-05-10",
        "profile_saved": "✅ Profile saved 🎉",
        "updated": "✅ Updated",
        # Contact / Location
        "phone_saved": "📱 Phone number saved ✅",
        "location_updated": "🚀 Location updated successfully!",
        "registration_error": "❌ Registration error.",
        # Errors
        "register_first": "❌ Please register first.",
        "share_location_first": "❌ Please share your location first.",
        "no_nearby": "❌ No one nearby right now.",
        "error": "❌ An error occurred.",
        "register_first_answer": "❌ Please register first",
        "error_answer": "❌ Error",
        # Matches / Requests
        "no_matches": "No matches yet 🔥",
        "matches_title": "🔥 Your matches:\n\n",
        "no_requests": "No likes yet 📥",
        "requests_title": "📥 People who liked you:\n\n",
        # Visibility
        "account_visible": "✅ Your account is now visible.",
        "account_hidden": "👻 Your account is now hidden.",
        "phone_visible": "📞 Your phone is now visible.",
        "phone_hidden": "🔒 Your phone is now hidden.",
        # Edit profile
        "what_to_edit": "✏️ What would you like to edit?",
        "enter_birthdate_edit": "🎂 Enter date:\n1998-05-10",
        "enter_bio_edit": "📝 Write your new bio:",
        # Card
        "user_label": "User",
        "unknown_gender": "Unknown",
        "gender_male": "Male",
        "gender_female": "Female",
        "unknown_distance": "Unknown",
        "active_now": "🟢 Active now",
        "last_seen": "🕒 {} {} ago",
        "unknown_label": "Unknown",
        # Card units
        "years_unit": "yo",
        "km_unit": "km",
        "min_unit": "min",
        "hour_unit": "h",
        "day_unit": "d",
        "now_unit": "now",
        # Mutual match
        "mutual_match": "🎉 It's a match! You can now chat.",
        # Answers
        "answer_liked": "Liked ❤️",
        "answer_match": "🎉 Match!",
        "answer_superlike": "⭐ Super like!",
        # Main keyboard buttons
        "btn_share_phone": "📱 Register Phone",
        "btn_share_location": "📍 Share Location",
        "btn_view_nearby": "👥 View Nearby",
        "btn_matches": "🔥 Matches",
        "btn_requests": "📥 My Likes",
        "btn_hide": "👻 Hide Account",
        "btn_phone_toggle": "📞 Show/Hide Phone",
        "btn_edit": "✏️ Edit Profile",
        # Card buttons
        "btn_prev": "⬅️ Prev",
        "btn_next": "Next ➡️",
        "btn_like": "❤️ Like",
        "btn_superlike": "⭐ Super",
        "btn_skip": "❌ Skip",
        "btn_message": "💬 Message",
        # Edit keyboard buttons
        "btn_edit_gender": "👤 Edit Gender",
        "btn_edit_birthdate": "🎂 Edit Birthdate",
        "btn_edit_bio": "📝 Edit Bio",
        # Last seen label
        "last_seen_label": "Last seen:",
        # Map
        "btn_map": "🗺️ Map",
        "map_tap": "🗺️ Tap to open the interactive map\n\n📍 Your location = red pin\n🔵 Nearby users = blue pins\nTap any blue pin to view their profile",
        "map_btn_open": "🗺️ Open Map",
        "map_no_location": "❌ Please share your location first, then open the map.",
        "map_not_registered": "❌ Please register first.",
        # Profile
        "btn_profile": "👤 My Profile",
        "profile_tap": "👤 Tap to open your profile",
        "profile_btn_open": "👤 Open Profile",
        # Settings
        "btn_settings": "⚙️ Settings",
        "settings_tap": "⚙️ Tap to open the settings page",
        "settings_btn_open": "⚙️ Open Settings",
        # Rooms nearby & create
        "btn_rooms_nearby": "📍 Rooms Nearby",
        "btn_create_room": "🏠 Create Room",
        "room_loc_snapshot":  "📍 Your current location will be saved as the room's fixed location.\n\n",
        "room_no_location":   "⚠️ Your location was not found. Open the map first to enable location — the room will be created without coordinates and may not appear on the map.\n\n",
        "create_room_ask_name": "🏠 Enter a name for your room:",
        "create_room_ask_purpose": "📝 Describe the purpose of your room:",
        "room_created": "✅ Room created!\n🏠 Name: {}\n📝 Purpose: {}",
        "room_create_error": "❌ Error creating room. Make sure the database table exists.",
        "room_join_request": "📩 New join request for your room «{}» from @{}",
        "btn_accept": "✅ Accept",
        "btn_reject": "❌ Reject",
        "room_accepted": "✅ Join request accepted.",
        "room_rejected": "❌ Join request rejected.",
        "room_you_accepted": "✅ You were accepted into room «{}»!",
        "room_you_rejected": "❌ Your request to join «{}» was rejected.",
        "room_cancel": "❌ Room creation cancelled.",
        "btn_cancel_action": "❌ Cancel",
        "create_room_ask_nature": "🏷️ Choose the room type:",
        "nature_social": "🤝 Social",
        "nature_edu": "📚 Educational",
        "nature_fun": "🎭 Entertainment",
        "nature_work": "💼 Work",
        "nature_sport": "⚽ Sports",
        "nature_other": "📌 Other",
        "create_room_ask_expires": "⏳ How long should this room be active?",
        "expires_1d": "⏰ 1 Day",
        "expires_3d": "📅 3 Days",
        "expires_1w": "🗓️ 1 Week",
        "expires_1m": "📆 1 Month",
        "expires_forever": "♾️ Forever",
        "room_join_ok": "✅ You joined room «{}» successfully!",
        "room_join_already": "ℹ️ You are already a member of this room.",
        "room_join_error": "❌ Error joining the room.",
        "room_delete_ok": "🗑️ Room deleted successfully.",
        "room_delete_no_perm": "❌ Cannot delete: you are not the creator or there are other members.",
        "room_delete_error": "❌ Error deleting the room.",
        "room_image_ok": "✅ Room image saved.",
        "room_image_del_ok": "✅ Room image deleted.",
        # Users list
        "btn_users_list": "👥 Users List",
        "users_tap": "👥 Tap to browse nearby users",
        "users_btn_open": "👥 Open List",
        "users_no_location": "❌ Please share your location first, then open the list.",
        "users_not_registered": "❌ Please register first.",
        # Rooms list
        "btn_rooms_list": "🏠 Rooms List",
        "rooms_list_tap": "🏠 Tap to browse nearby rooms",
        "rooms_list_btn_open": "🏠 Open Rooms List",
        "rooms_list_no_location": "❌ Please share your location first, then open the rooms list.",
        "rooms_list_not_registered": "❌ Please register first.",
        "room_limit_reached": "❌ You've reached the max limit (3 rooms). Delete a room first.",
        # Stores
        "btn_stores_list": "🏪 Stores List",
        "btn_create_store": "🛍️ Create Store",
        "btn_stores_nearby": "📍 Stores Nearby",
        "stores_list_tap": "🏪 Tap to browse nearby stores",
        "stores_list_btn_open": "🏪 Open Stores List",
        "stores_list_no_location": "❌ Please share your location first, then open the stores list.",
        "stores_list_not_registered": "❌ Please register first.",
        "store_limit_reached": "❌ You've reached the max limit (3 stores). Delete a store first.",
        "store_loc_snapshot":  "📍 Your current location will be saved as the store's fixed location.\n\n",
        "store_no_location":   "⚠️ Your location was not found. Open the map first to enable location — the store will be created without coordinates and may not appear on the map.\n\n",
        "create_store_ask_name": "🏪 Enter a name for your store:",
        "create_store_ask_purpose": "📝 Describe your store (what do you sell?):",
        "create_store_ask_nature": "🏷️ Choose the store type:",
        "store_nature_grocery": "🛒 Grocery",
        "store_nature_food": "🍔 Restaurant / Food",
        "store_nature_clothing": "👕 Clothing",
        "store_nature_electronics": "📱 Electronics",
        "store_nature_beauty": "💄 Beauty & Care",
        "store_nature_services": "🔧 Services",
        "store_nature_other": "📦 Other",
        "create_store_ask_expires": "⏳ How long should the store be listed?",
        "store_created": "✅ Store created!\n🏪 Name: {}\n📝 Description: {}",
        "store_create_error": "❌ Error creating the store. Make sure the database is ready.",
        "store_cancel": "❌ Store creation cancelled.",
        "nearby_stores": "📍 Nearby Stores:",
        # Chat system
        "btn_public_chat":     "💬 Public Chat",
        "btn_room_chats":      "🏠 Room Chats",
        "btn_store_chats":     "🏪 Store Chats",
        "btn_exit_chat":       "❌ Exit Chat",
        "chat_select_room":    "🏠 Choose a room to chat in:",
        "chat_select_store":   "🏪 Choose a store to chat in:",
        "chat_no_rooms":       "❌ You are not a member of any room. Join a room first.",
        "chat_no_stores":      "❌ You are not following any store. Follow a store first.",
        "chat_room_joined":    "✅ You joined the group chat of room «{}»\n\nSend any message, photo, file or sticker — it will reach all members.\n\nPress the button below to exit.",
        "chat_store_joined":   "✅ You joined the group chat of store «{}»\n\nSend any message, photo, file or sticker — it will reach all followers.\n\nPress the button below to exit.",
        "chat_exited":         "✅ You left the chat.",
        "chat_from":           "💬 {} — Room «{}»",
        "chat_from_store":     "🏪 {} — Store «{}»",
        "chat_private_from":   "🔒 Private message from {}",
        "chat_btn_private":    "💬 Private Chat",
        "chat_btn_reply":      "↩️ Reply Privately",
        "chat_btn_exit":       "❌ Exit Chat",
        "chat_private_started":"🔒 Private chat started with {}\nSend any message and it will go directly to them.\nPress the button below to exit.",
        "chat_private_notify": "🔒 {} started a private chat with you.",
        "chat_no_members":     "ℹ️ No other members in this room/store right now.",
    },
}


def T(lang: str, key: str, *args) -> str:
    lang = lang if lang in TEXTS else "en"
    text = TEXTS[lang].get(key) or TEXTS["en"].get(key, key)
    if args:
        return text.format(*args)
    return text


def detect_lang(language_code: str) -> str:
    if language_code and language_code.startswith("ar"):
        return "ar"
    return "en"


# All possible button texts (both languages) for regex matching in main.py
ALL_BTN = {
    "view_nearby":    ["👥 عرض الأقرب",            "👥 View Nearby"],
    "matches":        ["🔥 التطابقات",              "🔥 Matches"],
    "requests":       ["📥 طلباتي",                 "📥 My Likes"],
    "edit_gender":    ["👤 تعديل النوع",             "👤 Edit Gender"],
    "edit_birthdate": ["🎂 تعديل تاريخ الميلاد",    "🎂 Edit Birthdate"],
    "edit_bio":       ["📝 تعديل النبذة",            "📝 Edit Bio"],
    "map":            ["🗺️ الخريطة",                 "🗺️ Map"],
    "users_list":     ["👥 قائمة المستخدمين",        "👥 Users List"],
    "rooms_nearby":   ["📍 الغرف القريبة",             "📍 Rooms Nearby"],
    "rooms_list":     ["🏠 قائمة الغرف",               "🏠 Rooms List"],
    "create_room":    ["🏠 إنشاء غرفة",               "🏠 Create Room"],
    "stores_list":    ["🏪 قائمة المتاجر",              "🏪 Stores List"],
    "create_store":   ["🛍️ إنشاء متجر",               "🛍️ Create Store"],
    "stores_nearby":  ["📍 المتاجر القريبة",            "📍 Stores Nearby"],
    "cancel_action":  ["❌ إلغاء",                     "❌ Cancel"],
    "profile":        ["👤 ملفي الشخصي",               "👤 My Profile"],
    "settings":       ["⚙️ الإعدادات",                 "⚙️ Settings"],
    "room_chats":     ["💬 دردشة الغرف",               "💬 Room Chats"],
    "store_chats":    ["💬 دردشة المتاجر",              "💬 Store Chats"],
    "exit_chat":      ["❌ خروج من الدردشة",            "❌ Exit Chat"],
    "public_chat":    ["💬 الدردشة العامة",              "💬 Public Chat"],
}


def btn_regex(key: str) -> str:
    options = "|".join(ALL_BTN[key])
    return f"^({options})$"
